travis:
  secure:
    BINSTAR_TOKEN: a6yxI+mn9d9LKmSOPnOuGSS6+BQL0Bt3YZW3QqNT5WcL0NK2M6+mCcaydLLsBA0XZbgZJ+iVTngM1qx7gIa5nWHcJHm6mB86GHuLtZsMptdm3vnbpIHOj0zT+a3N59WEsensY0PUZ6cvHxm0UCQFNKmckM/csMnSZVdRiMrmGxs9+3wylw3mpNpYNzxM53Lai3cJfKP6TGbtzmEOk2xqHT6bN3xc6XKc+6966GLju1x07pJVFJhFnwM5lSJJTymXNH+VgGf5Q8UFLoq5LbejuphuFma5hva3lvkZ6Ms97Q/rDPYGv4deVqoRO+ARAUd22Ram7Qjhv6VM2W+N0KVx8JS5OFMUL4MSzJGNY0HbsmcU57b6VsxqpJNr62ppNnSY6ZRqk3OweC2dERO/sYqHxsE4jZ0ikvkMOoc7aHGb16uAed8WY4Dm5SzLUzKRsmNlpG3CLaPEMXuzaXP9FVdZeCf5RWsxQzQCzYL0bjJRy84c7EZaac+1Be8OVAOcL7rYn7zu6ZB9oNm52fDoTr8WYVHaeLcjr6sReqbUkOjZZQP1H80/3rGTCB+RsMBEEQrHlpHGbNLO0QA6Iebn2CtuB3Yk7NInq1iHQRs/1k4YatMRtUMRIkJ3vh8DAXBi+V6gZvVotpSr1x+GIwsjOcd1oqNplmR2U/sJdlje9vctoaA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
